# Generated by Django 5.1.4 on 2025-01-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_touristspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='image',
        ),
    ]
