# Generated by Django 5.1.4 on 2025-01-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_touristspot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='touristspot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.touristspot'),
            preserve_default=False,
        ),
    ]
