# Generated by Django 5.1.4 on 2025-01-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_review_touristspot_review_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='destination_id',
        ),
    ]
