# Generated by Django 5.1.4 on 2025-01-21 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_activity_destination_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='activity',
        ),
        migrations.AddField(
            model_name='review',
            name='activity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.activity'),
            preserve_default=False,
        ),
    ]
