# Generated by Django 5.1.4 on 2025-01-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_review_activity_review_activity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='activity_id',
            new_name='type_of_Activity',
        ),
    ]
