# Generated by Django 5.1.4 on 2025-01-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_activity_id_review_type_of_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TouristSpot',
        ),
    ]
