# Generated by Django 5.1.4 on 2025-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_touristspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.TextField(),
        ),
    ]
