# Generated by Django 5.1.4 on 2025-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_review_location_alter_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
